TB_TG/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="TB_TG",
        default_version="v1",
        description="Online Shop",
        terms_of_service="",
        contact=openapi.Contact(email="yosofasady2@gmail.com"),
    ),
    public=True,
)

"""https://automationpanda.com/2018/04/21/django-admin-translations/"""

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('api-v1/', include('shop.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path("core/", include('core.urls', namespace='core')),
    path("", include('front.urls', namespace='front')),
    path("blog/", include('blog.urls', namespace='blog')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('conversations/', include('chat.urls')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

blog/urls.py
from django.urls import path
from rest_framework_nested import routers
from .views import BlogViewSet, BlogCommentViewSet

router = routers.DefaultRouter()
router.register(r'blogs', BlogViewSet, basename='blogs')
blog = routers.NestedDefaultRouter(router, 'blogs', lookup='blog')

blog.register(r'comments', BlogCommentViewSet, basename='blog_comments')

app_name = 'blog'
urlpatterns = [
    *router.urls,
    *blog.urls
]

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('start/', views.start_conversation, name='start_conversation'),
    path('<int:convo_id>/', views.get_conversation, name='get_conversation'),
    path('', views.conversations, name='conversations')
]

front/urls.py
from django.urls import path, include
from . import views

app_name = 'front'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('verify-otp/', views.VerifyOtpView.as_view(), name='verify-otp'),
    path('set-password/', views.SetPasswordView.as_view(), name='set-password'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('products/<int:id>/', views.ProductDetailView.as_view(), name='products-detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('order-detail/<int:id>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('compare/', views.CompareView.as_view(), name='compare'),
    path('', views.HomeView.as_view(), name='home'),
    # path('', views.cached_template_home_view, name='home'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('set_language/', views.set_language, name='set_language'),
    path('blogs/<int:id>/', views.cached_template_blog_detail_view, name='blog_detail'),
    path('blogs/', views.cached_template_blog_list_view, name='blogs'),
    path('chat/', views.ChatView.as_view(), name='chat'),
    path('chat/admin', views.ChatAdminView.as_view(), name='chat-admin'),

]

blog/models.py
from django.db import models
from parler.models import TranslatableModel, TranslatedFields
from django.utils.translation import gettext_lazy as _
from core.models import BaseModel
from shop.models import Customer


class Blog(TranslatableModel, BaseModel):
    """
    Model representing a blog post.

    Attributes:
        title (CharField): The title of the blog post.
        body (TextField, optional): The body/content of the blog post.
        thumbnail (ImageField): The thumbnail image associated with the blog post.
        views (IntegerField): The number of views the blog post has received.
        author (ForeignKey): The author of the blog post.
    """
    translations = TranslatedFields(
        title=models.CharField(_("Title"), max_length=255, unique=True),
        body=models.TextField(_("Body"), null=True, blank=True)
    )
    thumbnail = models.ImageField(_('Thumbnail'), upload_to='blogs/thumbnail/')
    views = models.IntegerField(_('Views'), default=0)
    author = models.ForeignKey(Customer, on_delete=models.PROTECT, verbose_name=_('Author'))

    def __str__(self):
        return f"{self.title} - {self.author}"

    class Meta:
        verbose_name = _("Blog")
        verbose_name_plural = _("Blogs")


class BlogComment(BaseModel):
    """
    Model representing a comment on a blog post.

    Attributes:
        customer (ForeignKey): The customer who left the comment.
        blog (ForeignKey): The blog post on which the comment is made.
        subject (CharField): The subject/title of the comment.
        message (TextField): The content/message of the comment.
        active (BooleanField): Indicates whether the comment is active.
    """
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name=_("Customer"))
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name=_("Blog"), related_name='comments')
    subject = models.CharField(_("Subject"), max_length=255)
    message = models.TextField(_("Message"))
    active = models.BooleanField(_("Active"), default=False)

    def __str__(self):
        return f"{self.customer} - {self.subject}"

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

chat/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _


# Create your models here.

class Conversation(models.Model):
    sender_conversation = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                                            related_name="sender_conversation")
    receiver_conversation = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                                              related_name="receiver_conversation")
    start_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("Conversation")
        verbose_name_plural = _("Conversations")


class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                               null=True, related_name='message_sender')
    text = models.CharField(max_length=200, blank=True)
    attachment = models.FileField(blank=True)
    conversation_id = models.ForeignKey(Conversation, on_delete=models.CASCADE, )
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-timestamp',)
        verbose_name = _("Message")
        verbose_name_plural = _("Messages")

blog/views.py
from rest_framework import viewsets, filters, mixins
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from blog.models import BlogComment, Blog
from blog.serializers import BlogSerializer, BlogCommentSerializer
from shop.pagination import DefaultBlogPagination


# Create your views here.
class BlogViewSet(mixins.RetrieveModelMixin,
                  mixins.ListModelMixin,
                  GenericViewSet):
    queryset = Blog.objects.all().prefetch_related('author', 'comments')
    serializer_class = BlogSerializer
    pagination_class = DefaultBlogPagination
    filter_backends = [filters.SearchFilter]
    search_fields = ['translations__title', 'translations__body']
    ordering = ['-updated_at']

    # https://stackoverflow.com/questions/56228485/how-can-i-make-a-view-count-in-django-rest-framework
    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.views += 1
        instance.save()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)


class BlogCommentViewSet(viewsets.ModelViewSet):
    serializer_class = BlogCommentSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['subject', 'message']
    ordering = ['-updated_at']
    permission_classes = [IsAuthenticatedOrReadOnly]

    def get_serializer_context(self):
        return {'blog_id': self.kwargs['blog_pk'], 'user_id': self.request.user.id}

    def get_queryset(self):
        print(self.kwargs)
        return BlogComment.objects.all().select_related('customer', 'blog').filter(blog_id=self.kwargs['blog_pk'],
                                                                                   active=True)

chat/views.py
from .models import Conversation
from rest_framework.response import Response
from core.models import User
from .serializers import ConversationListSerializer, ConversationSerializer
from django.db.models import Q
from django.shortcuts import redirect, reverse
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from django.db.utils import IntegrityError


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def start_conversation(request, ):
    """
    {
        "phone_number": "09353220545"
    }
    """
    data = request.data
    print(data)
    phone_number = data.pop('phone_number')
    print(phone_number)
    try:
        participant = User.objects.get(phone_number=phone_number)
    except User.DoesNotExist:
        return Response({'message': 'You cannot chat with a non existent user'})

    conversation = Conversation.objects.filter(Q(sender_conversation=request.user, receiver_conversation=participant) |
                                               Q(sender_conversation=participant, receiver_conversation=request.user))
    print(conversation.query)
    print('conversation', conversation)
    print('user', request.user)
    if conversation.exists():
        return redirect(reverse('get_conversation', args=(conversation[0].id,)))
    else:
        conversation = Conversation.objects.create(id=request.user.id, sender_conversation=request.user,
                                                   receiver_conversation=participant)
        return Response(ConversationSerializer(sender_conversation=conversation).data)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_conversation(request, convo_id):
    user = User.objects.get(id=request.user.id)
    if user.is_staff or user.is_superuser:
        conversation = Conversation.objects.filter(id=convo_id)
    else:
        conversation = Conversation.objects.filter(
            Q(id=convo_id) & (Q(sender_conversation=user) | Q(receiver_conversation=user))
        )
    if not conversation.exists():
        return Response({'message': 'Conversation does not exist'})
    else:
        serializer = ConversationSerializer(instance=conversation[0])
        return Response(serializer.data)


@api_view(['GET'])
@permission_classes([IsAdminUser])
def conversations(request):
    if request.user.is_staff or request.user.is_superuser:
        conversation_list = Conversation.objects.all()
    else:
        conversation_list = Conversation.objects.filter(Q(sender_conversation=request.user) |
                                                        Q(receiver_conversation=request.user))
    serializer = ConversationListSerializer(instance=conversation_list, many=True)
    return Response(serializer.data)

front/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.shortcuts import render
from django.utils.translation import activate
from django.views import View
from django.views.decorators.vary import vary_on_headers
from django.views.generic import TemplateView
from django.conf import settings
import requests
import json


# Create your views here.
class LoginView(TemplateView):
    template_name = 'login.html'


class VerifyOtpView(TemplateView):
    template_name = 'verify_otp.html'


class SetPasswordView(TemplateView):
    template_name = 'set_password.html'


class RegisterView(TemplateView):
    template_name = 'register.html'


class ProductListView(TemplateView):
    template_name = 'products_list.html'


class ProductDetailView(View):
    template_name = 'products_detail.html'

    def get(self, request, id):
        return render(request, self.template_name, {'id': id})


class CartView(TemplateView):
    template_name = 'cart.html'


class BlogListView(TemplateView):
    template_name = 'blogs.html'


cached_template_blog_list_view = cache_page(60 * 60 * 10)(BlogListView.as_view())


class BlogDetailView(View):
    template_name = 'blog_detail.html'

    def get(self, request, id):
        return render(request, self.template_name, {'id': id})


cached_template_blog_detail_view = cache_page(60 * 60 * 10)(BlogDetailView.as_view())


class HomeView(TemplateView):
    template_name = 'index.html'


# cached_template_home_view = cache_page(60 * 15)(HomeView.as_view())


class ProfileView(TemplateView):
    template_name = 'profile.html'

    @method_decorator(cache_page(60 * 15))
    @method_decorator(vary_on_headers("Authorization"))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CompareView(TemplateView):
    template_name = 'compare.html'


class ChatView(TemplateView):
    template_name = 'chat.html'


class ChatAdminView(TemplateView):
    template_name = 'chatadmin.html'


class OrderDetailView(View):
    template_name = 'order_detail.html'

    def get(self, request, id):
        return render(request, self.template_name, {'id': id})


def set_language(request):
    if request.method == 'POST':
        language_code = request.POST.get('language_code')
        request.session['language_code'] = language_code
        settings.LANGUAGE_CODE = language_code
        activate(language_code)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

front/templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load compress %}
{% load cache %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_CODE == "fa" %}dir="rtl"{% endif %}>
{#<html lang="en">#}
<head>


    {% block js %}{% endblock %}


    <meta charset="UTF-8">

    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="">
    <!-- Author Meta -->
    <meta name="author" content="CodePixar">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>TB_TG Shop</title>
    <meta name="description" content="Y.A.A"/>
    <meta name="author" content="Y.A.A"/>

    <!--
        CSS
        ============================================= -->
    {#        {% static 'css/owl.carousel.css' %}#}
    {% compress css %}
        <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
        <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endcompress %}
</head>
<body>
    <header class="header_area sticky-header">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light main_box">
                <form class="m-4" id="language-form" action="{% url 'front:set_language' %}" method="post">
                    {% csrf_token %}
                    <input class="self" type="submit" name="language_code" value="fa">
                    <input type="submit" name="language_code" value="en">
                </form>
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <a id="logo_top" class="navbar-brand logo_h" href="{% url 'front:home' %}">
                        <img id="logoImage" class="img-fluid" style="width: 110px" src=""
                             alt="">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            <li class="nav-item mx-3"><a class="nav-link"
                                                         href="{% url 'front:home' %}">{% trans 'Home' %}</a>
                            </li>
                            <li class="nav-item submenu dropdown mx-3">
                                <a href="{% url 'front:products' %}" class="nav-link dropdown-toggle"
                                   role="button">{% trans 'Shop' %}</a>
                                {#								<ul class="dropdown-menu">#}
                                {#									<li class="nav-item"><a class="nav-link" href="category.html">Shop Category</a></li>#}
                                {#									<li class="nav-item"><a class="nav-link" href="single-product.html">Product Details</a></li>#}
                                {#									<li class="nav-item"><a class="nav-link" href="checkout.html">Product Checkout</a></li>#}
                                {#									<li class="nav-item"><a class="nav-link" href="cart.html">Shopping Cart</a></li>#}
                                {#									<li class="nav-item"><a class="nav-link" href="confirmation.html">Confirmation</a></li>#}
                                {#								</ul>#}
                            </li>
                            <li class="nav-item submenu dropdown mx-3">
                                <a href="{% url 'front:blogs' %}"
                                   class="nav-link dropdown-toggle">{% trans 'Blog' %}</a>
                            </li>
                            <li class="nav-item mx-3"><a class="nav-link"
                                                         href="{% url 'front:login' %}">{% trans 'Login / Register' %}</a>
                            </li>
                            <li class="nav-item mx-3"><a class="nav-link"
                                                         href="https://yousofasadi.vercel.app/">{% trans 'About Me' %}</a>
                            </li>
                            <li class="nav-item mx-3"><a class="nav-link"
                                                         href="{% url 'front:chat' %}">{% trans 'Support' %}</a>
                            </li>

                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item"><a href="{% url 'front:cart' %}" class="cart"><span
                                    class="ti-bag"></span></a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item"><a href="{% url 'front:profile' %}" class="user-details"><span
                                    class="ti-user"></span></a></li>
                            <li class="nav-item">
                                <button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container">
                <form class="d-flex justify-content-between">
                    <input type="text" class="form-control" id="search_input" placeholder="{% trans 'Search Here' %}">
                    <button type="submit" class="btn"></button>
                    <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
{% block contents %}

{% endblock %}

    <footer class="footer-area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>{% trans 'About Us' %}</h6>
                        <p id="aboutUsText"></p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>{% trans 'Address' %}</h6>
                        <p id="addressText"></p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6"></div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>{% trans 'Follow Us' %}</h6>
                        <p>{% trans 'Let us be social' %}</p>
                        <div class="footer-social d-flex align-items-center">
                            <a href="#" id="telegramLink"><i class="fa fa-telegram"></i></a>
                            <a href="#" id="instagramLink"><i class="fa fa-instagram"></i></a>
                            <a href="#" id="whatsappLink"><i class="fa fa-whatsapp"></i></a>
                            <a href="#" id="twitterLink"><i class="fa fa-twitter"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
                <p class="footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                        href="https://github.com/Y-A-Asd" target="_blank">Y-A-Asd</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                console.log('{{ LANGUAGE_CODE }}')
                fetch("/api-v1/site-settings/")
                    .then(response => response.json())
                    .then(data => {
                        const siteSettings = data[0];

                        document.getElementById("aboutUsText").textContent = siteSettings.footer_text;

                        document.getElementById("addressText").textContent = siteSettings.address;

                        document.getElementById("telegramLink").href = siteSettings.telegram_link;
                        document.getElementById("instagramLink").href = siteSettings.instagram_link;
                        document.getElementById("whatsappLink").href = siteSettings.whatsapp_link;
                        document.getElementById("twitterLink").href = siteSettings.twitter_link;

                        const logoUrl = siteSettings.logo;
                        document.getElementById("logoImage").src = logoUrl;
                    })
                    .catch(error => console.error("Error fetching site settings:", error));
            });
        </script>
    </footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
{% compress js %}
    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>

    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/nouislider.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!--gmaps Js-->
    <script src="{% static 'js/gmaps.min.js' %}"></script>
{% endcompress %}

</body>
</html>

front/templates/compare.html
{% extends 'base.html' %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load static %}
{% block contents %}
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1 class="text-danger">{% trans 'Compare' %}</h1>
                    <nav class="d-flex align-items-center">
                        <a class="text-danger" href="{% url 'front:home' %}">{% trans 'Home' %}<span
                                class="lnr lnr-arrow-right"></span></a>
                        <a class="text-danger" href="{% url 'front:products' %}">{% trans 'Shop' %}</a>
                        <a class="text-danger" href="">{% trans 'Compare' %}</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Cart Area =================-->
    <section class="cart_area">
        <div class="container">
            <div class="cart_inner">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

        <script>
            const getQueryParameters = () => {
                const searchParams = new URLSearchParams(window.location.search);
                const productIds = searchParams.getAll('product_ids');
                return productIds;
            }

            const fetchComparisonData = (productIds) => {
                const apiUrl = `/api-v1/compare/?product_ids=${productIds.join('&product_ids=')}`;
                return fetch(apiUrl)
                    .then(response => response.json());

            }


            const generateTable = (comparisonData) => {
                const productIds = getQueryParameters()

                const featureCount = Object.keys(comparisonData).length
                const productKey = Object.keys(comparisonData).slice(0, 1)
                const featureKey = Object.keys(comparisonData).filter(key => !productKey.includes(key))
                const productTitles = Object.keys(comparisonData[productKey[0]])
                console.log(featureCount)// 5
                console.log(productKey)// ['Title']
                console.log(featureKey)// ['Price', 'Collection', 'Color', 'Brand']
                console.log(productTitles)// ['Product 1', 'Product 2']
                console.log(comparisonData)

                const table = document.querySelector('.table');
                const thead = table.querySelector('thead');
                const tbody = table.querySelector('tbody');
                thead.innerHTML = ``
                tbody.innerHTML = ``

                const theadtr = document.createElement('tr');
                const theadth = document.createElement('th');
                const theadh = document.createElement('h6');
                theadh.textContent = '{% trans 'Title' %}'
                theadth.appendChild(theadh);
                theadtr.appendChild(theadth);

                productTitles.forEach(product => {
                    console.log(product)
                    const theadth = document.createElement('th');
                    theadth.textContent = product;
                    theadtr.appendChild(theadth);


                })
                thead.appendChild(theadtr);

                featureKey.forEach(feature => {
                    const tbodytr = document.createElement('tr');
                    const tbodytb = document.createElement('td');
                    const tbodyh = document.createElement('h6');
                    tbodyh.textContent = feature
                    tbodytb.append(tbodyh)
                    tbodytr.append(tbodytb)
                    productTitles.forEach(key => {
                        value = comparisonData[feature][key]
                        const tbodytb = document.createElement('td');
                        tbodytb.textContent = value
                        tbodytr.append(tbodytb)


                    })
                    tbody.appendChild(tbodytr);


                })
                const tbodytr = document.createElement('tr');
                const tbodytb = document.createElement('tb');

            }

            document.addEventListener('DOMContentLoaded', () => {
                const productIds = getQueryParameters();
                fetchComparisonData(productIds)
                    .then(comparisonData => generateTable(comparisonData));
            });
        </script>
    <!--================End Cart Area =================-->
{% endblock %}